[package]
name = "xpop"
version = "0.3.0"
edition = "2024"
authors = ["Koosha Hosseiny <git@koosha.io>"]
description = "An X11 pull-down application toggler"
homepage = "https://koosha.io/project/xpop"
license = "GPL-3.0"
readme = "README.md"
repository = "https://gitlab.com/hkoosha/xpop"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[lints.clippy]
needless_return = "allow"

[dependencies]
thiserror = "2.0"
clap = { version = "4", features = ["derive"] }
dbus = { version = "0.9", features = ["stdfd"] }
dbus-crossroads = "0.5"
x11rb = { version = "0.14", features = ["allow-unsafe-code"] }
