array_width = 0
control_brace_style = "ClosingNextLine"
fn_params_layout = "Vertical"
trailing_semicolon = true
imports_layout = "Vertical"
max_width = 80
reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "module"
